import SideBAr from "@/components/sideBar/SideBar";
import "./globals.css";
import { Inter } from "next/font/google";
import FollowBar from "@/components/followBar/FollowBar";
import LoginModal from "@/components/modals/LoginModal";
import RegisterModal from "@/components/modals/RegisterModal";
import TweetModal from "@/components/modals/TweetModal";
import Toast from "@/components/toasts/Toasts";
import userStore from "@/stores/server/userStore";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import SyncClientStore from "@/components/sync/SyncClientStore";
import client from "@/libs/prismaClient";
import EditModal from "@/components/modals/EditModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  if (session) {
    const { id } = await client.user.findUnique({
      where: {
        email: session.user.email,
      },
    });
    userStore.user = { ...session?.user, id };
    userStore.loggedIn = true;
  } else {
    userStore.user = null;
    userStore.loggedIn = false;
  }

  console.log(userStore?.user?.name, "userstore layout");

  const loggedIn = userStore.loggedIn;

  return (
    <html lang="en" data-theme="dark">
      <body className={`${inter.className} `}>
        {loggedIn && <SyncClientStore />}
        <LoginModal />
        <RegisterModal />
        <TweetModal />
        <EditModal />
        <Toast />
        <div className="xl:px-24 md:px-10 px-4 h-full min-h-screen ">
          <div className="grid grid-cols-12 gap-0 border-x-[1px] h-full min-h-screen border-neutral-400 ">
            <div className="xl:col-span-3 col-span-2 pt-1 ">
              <SideBAr loggedIn={loggedIn} />
            </div>

            <div className="xl:col-span-6 col-span-9 border-x-[1px] border-neutral-400 pt-1 overflow-y-scroll ">
              {children}
            </div>
            <div className="col-span-3 xl:block hidden pt-1 ">
              <FollowBar />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
